name = "spidersnet-logo-generator"  # Name of your Cloudflare project
type = "javascript"          # Type of the project (JavaScript, TypeScript, etc.)

# Specify the entry point
main = "functions/create-ticket.js"  # Path to your main function file

  compatibility_date = "2024-10-15"  # Same as above


[env.production]
  account_id = "fdc96013ff1bf45f7d2e7175767461bb"
  workers_dev = false  # False if deploying to a custom domain
  compatibility_date = "2024-10-15"  # Same as above

[build]
  functions = "./functions"  # Path to your functions directory

[vars]
CLICKUP_API = "BVIBNXPCE5WHT7SCJASY00O2ZH30YGT7"
CLICKUP_LIST = "901508351342"



[[deployments]]
  environment = "production"
  url = "https://spidersnet-logo-generator.workers.dev"  # URL of the deployed worker

