export const iconOptions = [
    {
        id: 1,
        url: "icons/icon_01.svg",
        category: "automotive",
        class: "style-1",
        slogan: false,
        fontFamily: 3,
        fontSize: 24,
        fontSpacing: 2,
    },
    {
        id: 2,
        url: "icons/icon_02.svg",
        category: "automotive",
        class: "style-2",
        slogan: false,
        fontFamily: 17,
        fontSize: 30,
        fontSpacing: 1,
    },
    {
        id: 3,
        url: "icons/icon_03.svg",
        category: "automotive",
        class: "style-3",
        slogan: false,
        iconHeight: 48,
        iconWidth: 139,
        fontFamily: 4,
        fontSize: 30,
        fontSpacing: 1.5,
    },
    {
        id: 4,
        url: "icons/icon_04.svg",
        category: "automotive",
        class: "style-4",
        slogan: false,
        fontFamily: 17,
        fontSize: 30,
        fontSpacing: 1,
    },
    {
        id: 5,
        url: "icons/icon_05.svg",
        category: "automotive",
        class: "style-5",
        slogan: false,
        fontFamily: 5,
        fontSize: 25,
        fontSpacing: 1,
    },
    {
        id: 6,
        url: "icons/icon_06.svg",
        category: "automotive",
        class: "style-6",
        slogan: false,
        fontFamily: 7,
        fontSize: 24,
        fontSpacing: 3,
    },
    {
        id: 7,
        url: "icons/icon_07.svg",
        category: "automotive",
        class: "style-7",
        slogan: false,
        fontFamily: 8,
        fontSize: 27,
        fontSpacing: 0,
    },
    {
        id: 8,
        url: "icons/icon_08.svg",
        category: "automotive",
        class: "style-8",
        slogan: false,
        fontFamily: 20,
        fontSize: 25,
        fontSpacing: 1,
    },
    {
        id: 9,
        url: "icons/icon_09.svg",
        category: "automotive",
        class: "style-9",
        slogan: false,
        fontFamily: 9,
        fontSize: 25,
        fontSpacing: 3,
    },
    {
        id: 10,
        category: "typography",
        class: "style-10",
        slogan: true,
        fontFamily: 10,
        fontSize: 22,
        fontSpacing: 3.5,
    },
    {
        id: 11,
        category: "typography",
        class: "style-11",
        slogan: false,
        fontFamily: 19,
        fontSize: 25,
        fontSpacing: 1,
    },
    {
        id: 12,
        category: "typography",
        class: "style-12",
        slogan: true,
        fontFamily: 9,
        fontSize: 31,
        fontSpacing: 3,
    },
    {
        id: 13,
        url: "icons/icon_13.svg",
        category: "typography",
        class: "style-13",
        slogan: true,
        fontFamily: 11,
        fontSize: 25,
        fontSpacing: 0,
    },
    {
        id: 14,
        category: "typography",
        class: "style-14",
        slogan: true,
        fontFamily: 12,
        fontSize: 26,
        fontSpacing: 0,
    },
    {
        id: 15,
        category: "typography",
        class: "style-15",
        slogan: true,
        fontFamily: 13,
        fontSize: 23,
        fontSpacing: 3,
    },
    {
        id: 16,
        category: "typography",
        class: "style-16",
        slogan: true,
        fontFamily: 14,
        fontSize: 24,
        fontSpacing: 3,
    },
    {
        id: 17,
        category: "typography",
        class: "style-17",
        slogan: true,
        fontFamily: 15,
        fontSize: 22,
        fontSpacing: 3.5,
    },
    {
        id: 18,
        category: "typography",
        class: "style-18",
        slogan: true,
        fontFamily: 16,
        fontSize: 27,
        fontSpacing: 4,
    },
]