export const iconOptions = [
    {
        id: 1,
        url: "icons/icon_01.svg",
        category: "automotive",
        slogan: false,
        fontFamily: "Georama",
        fontSize: 24,
        fontSpacing: 2,
    },
    {
        id: 2,
        url: "icons/icon_02.svg",
        category: "automotive",
        slogan: false,
        fontFamily: "Barlow",
        fontSize: 25,
        fontSpacing: 3,
    },
    {
        id: 3,
        url: "icons/icon_03.svg",
        category: "automotive",
        slogan: false,
        fontFamily: "Geologica",
        fontSize: 30,
        fontSpacing: 2,
    },
    {
        id: 4,
        url: "icons/icon_04.svg",
        category: "automotive",
        slogan: false,
        fontFamily: "Rubik One",
        fontSize: 21,
        fontSpacing: 1,
    },
    {
        id: 5,
        url: "icons/icon_05.svg",
        category: "automotive",
        slogan: false,
        fontFamily: "Spinnaker",
        fontSize: 24,
        fontSpacing: 1,
    },
    {
        id: 6,
        url: "icons/icon_06.svg",
        category: "automotive",
        slogan: true,
        fontFamily: "Spinnaker",
        fontSize: 31,
        fontSpacing: 1,
    },
    {
        id: 7,
        url: "icons/icon_07.svg",
        category: "automotive",
        slogan: true,
        fontFamily: "Sofia Sans",
        fontSize: 27,
        fontSpacing: 1,
    },
    {
        id: 8,
        url: "icons/icon_08.svg",
        category: "automotive",
        slogan: false,
        fontFamily: "REM",
        fontSize: 25,
        fontSpacing: 1,
    },
    {
        id: 9,
        url: "icons/icon_09.svg",
        category: "automotive",
        slogan: true,
        fontFamily: "Geologica",
        fontSize: 32,
        fontSpacing: 0.5,
    },
    {
        id: 10,
        url: "icons/icon_10.svg",
        category: "automotive",
        slogan: false,
        fontFamily: "Aoboshi One",
        fontSize: 20,
        fontSpacing: 4,
    },
    {
        id: 11,
        url: "icons/icon_11.svg",
        category: "automotive",
        slogan: false,
        fontFamily: "Outfit",
        fontSize: 20,
        fontSpacing: 2,
    },
    {
        id: 12,
        url: "icons/icon_12.svg",
        category: "automotive",
        slogan: false,
        fontFamily: "Questrial",
        fontSize: 29,
        fontSpacing: 0,
    },
    {
        id: 13,
        url: "icons/icon_13.svg",
        category: "automotive",
        slogan: false,
        fontFamily: "Montserrat",
        fontSize: 29,
        fontSpacing: 0,
    },
    {
        id: 14,
        url: "icons/icon_14.svg",
        category: "automotive",
        slogan: true,
        fontFamily: "Radley",
        fontSize: 25,
        fontSpacing: 2.5,
    },
    {
        id: 15,
        url: "icons/icon_15.svg",
        category: "automotive",
        slogan: true,
        fontFamily: "Abhaya Libre",
        fontSize: 30,
        fontSpacing: 0,
    },
    {
        id: 16,
        url: "icons/icon_16.svg",
        category: "automotive",
        slogan: false,
        fontFamily: "Syncopate",
        fontSize: 22,
        fontSpacing: 3,
    },
    {
        id: 17,
        url: "icons/icon_17.svg",
        category: "automotive",
        slogan: false,
        fontFamily: "REM",
        fontSize: 20,
        fontSpacing: 1.5,
    },
    {
        id: 18,
        url: "icons/icon_18.svg",
        category: "automotive",
        slogan: false,
        fontFamily: "Geologica",
        fontSize: 30,
        fontSpacing: 0,
    },
    {
        id: 19,
        category: "typographic",
        slogan: true,
        fontFamily: "Cardo",
        fontSize: 24,
        fontSpacing: 3.5,
    },
    {
        id: 20,
        category: "typographic",
        slogan: false,
        fontFamily: "Questrial",
        fontSize: 25,
        fontSpacing: 1,
    },
    {
        id: 21,
        category: "typographic",
        slogan: true,
        fontFamily: "Palanquin Dark",
        fontSize: 30,
        fontSpacing: 1.5,
    },
    {
        id: 22,
        category: "typographic",
        slogan: true,
        fontFamily: "Montserrat",
        fontSize: 25,
        fontSpacing: 0,
    },
    {
        id: 23,
        category: "typographic",
        slogan: true,
        fontFamily: "Spinnaker",
        fontSize: 26,
        fontSpacing: 0,
    },
    {
        id: 24,
        category: "typographic",
        slogan: true,
        fontFamily: "Aoboshi One",
        fontSize: 23,
        fontSpacing: 3,
    },
    {
        id: 25,
        category: "typographic",
        slogan: true,
        fontFamily: "REM",
        fontSize: 24,
        fontSpacing: 3.5,
    },
    {
        id: 26,
        category: "typographic",
        slogan: true,
        fontFamily: "Fredoka",
        fontSize: 22,
        fontSpacing: 3.5,
    },
    {
        id: 27,
        category: "typographic",
        slogan: true,
        fontFamily: "Radley",
        fontSize: 23,
        fontSpacing: 3.5,
    },
    {
        id: 28,
        category: "typographic",
        slogan: true,
        fontFamily: "Gruppo",
        fontSize: 20,
        fontSpacing: 3,
    },
    {
        id: 29,
        category: "typographic",
        slogan: true,
        fontFamily: "Syne",
        fontSize: 22,
        fontSpacing: 3.5,
    },
    {
        id: 30,
        category: "typographic",
        slogan: false,
        fontFamily: "Outfit",
        fontSize: 23,
        fontSpacing: 3.5,
    },
    {
        id: 31,
        category: "typographic",
        slogan: false,
        fontFamily: "Montserrat",
        fontSize: 16,
        fontSpacing: 2.5,
    },
    {
        id: 32,
        url: "icons/icon_32.png",
        category: "typographic",
        slogan: true,
        fontFamily: "Blinker",
        fontSize: 25,
        fontSpacing: 0.5,
        note: "The initial will be changed to match your company name by the designer",
    },
    {
        id: 33,
        category: "typographic",
        slogan: false,
        fontFamily: "Outfit",
        fontSize: 23,
        fontSpacing: 3.5,
    },
    {
        id: 34,
        url: "icons/icon_34.svg",
        category: "abstract",
        slogan: true,
        fontFamily: "Cardo",
        fontSize: 23,
        fontSpacing: 3.5,
    },
    {
        id: 35,
        url: "icons/icon_35.svg",
        category: "abstract",
        slogan: false,
        fontFamily: "Questrial",
        fontSize: 25,
        fontSpacing: 4,
    },
    {
        id: 36,
        url: "icons/icon_36.svg",
        category: "abstract",
        slogan: true,
        fontFamily: "Palanquin Dark",
        fontSize: 28,
        fontSpacing: 1.5,
        note: "The year can be changed by the designer",
    },
    {
        id: 37,
        url: "icons/icon_37.svg",
        category: "abstract",
        slogan: false,
        fontFamily: "Syne",
        fontSize: 22,
        fontSpacing: 2,
    },
    {
        id: 38,
        url: "icons/icon_38.svg",
        category: "abstract",
        slogan: false,
        fontFamily: "REM",
        fontSize: 26,
        fontSpacing: 0,
    },
    {
        id: 39,
        url: "icons/icon_39.svg",
        category: "abstract",
        slogan: true,
        fontFamily: "Aoboshi One",
        fontSize: 23,
        fontSpacing: 3,
        note: "The initial will be changed to match your company name by the designer",
    },
    {
        id: 40,
        url: "icons/icon_40.svg",
        category: "abstract",
        slogan: false,
        fontFamily: "Geologica",
        fontSize: 24,
        fontSpacing: 0,
    },
    {
        id: 41,
        url: "icons/icon_41.svg",
        category: "abstract",
        slogan: true,
        fontFamily: "Fredoka",
        fontSize: 25,
        fontSpacing: 4,
    },
    {
        id: 42,
        url: "icons/icon_42.svg",
        category: "abstract",
        slogan: false,
        fontFamily: "Sofia Sans Semi Condensed",
        fontSize: 30,
        fontSpacing: 1,
    },
    {
        id: 43,
        url: "icons/icon_43.svg",
        category: "abstract",
        slogan: false,
        fontFamily: "Montserrat",
        fontSize: 20,
        fontSpacing: 3,
    },
    {
        id: 44,
        url: "icons/icon_44.svg",
        category: "abstract",
        slogan: false,
        fontFamily: "Syne",
        fontSize: 20,
        fontSpacing: 3,
    },
    {
        id: 45,
        url: "icons/icon_45.svg",
        category: "abstract",
        slogan: false,
        fontFamily: "Outfit",
        fontSize: 21,
        fontSpacing: 3,
    },
    // {
    //     id: 46,
    //     url: "icons/icon_46.svg",
    //     category: "abstract",
    //     slogan: false,
    //     fontFamily: "Syncopate",
    //     fontSize: 22,
    //     fontSpacing: 0.5,
    // },
    {
        id: 47,
        url: "icons/icon_47.svg",
        category: "abstract",
        slogan: false,
        fontFamily: "Syncopate",
        fontSize: 23,
        fontSpacing: 2.5,
    },
    {
        id: 48,
        url: "icons/icon_48.svg",
        category: "abstract",
        slogan: true,
        fontFamily: "Archivo Black",
        fontSize: 36,
        fontSpacing: 0,
    },

]